//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoppingEntities : DbContext
    {
        public shoppingEntities()
            : base("name=shoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<cloth> clothes { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<kidprod> kidprods { get; set; }
        public virtual DbSet<menprod> menprods { get; set; }
        public virtual DbSet<womenprod> womenprods { get; set; }
        public virtual DbSet<accdet> accdets { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<usercart> usercarts { get; set; }
        public virtual DbSet<Userrole> Userroles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Reset> Resets { get; set; }
    }
}
